name: Release - Module

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release Version
        required: true
        default: 1.0.0

run-name: 'version set to ${{ inputs.release-version }} for release'

jobs:
  main:
    uses: codbex/codbex-infra/.github/workflows/module-release.yaml@main
    with:
      packages: codbex-hera-print
      packages-build: codbex-hera-print
      release-version: ${{ inputs.release-version }}
      release-content: |
        ## codbex-invoices - ${{ inputs.release-version }}
        
        Invoices Management Module
        
        ## Installation
        
        ```
        npm install @codbex/codbex-invoices@${{ inputs.release-version }}
        ```
        
        ## Access points:
        
        - [/services/web/codbex-hera-print/gen/](http://localhost:80/services/web/codbex-hera-print/gen/) - Admin Panel
    secrets: inherit